### PR TITLE
added mention to VarInts

### PR DESCRIPTION
**Pull request by bconstanzo**
Added mention to VarInts and that the used algorithm doesn't have any bit-length limitations in the encoding/decoding of the values.

### CODE REVIEW

**Review by facundobatista — CHANGES_REQUESTED** [review]
But it's not effectively a VarInt without restrictions, right? because tencdec one only encodes deltas (which is a key factor in its compression)

**Comment by bconstanzo** [comment]
Yes, it's the deltas that are encoded as VarInts in the stream of bytes that encodes the list, that could be clearer in the text.

**Comment by bconstanzo** [comment]
I rephrased a bit the text to explicitly mention the deltas so that it is clearer what goes on during compression.

**Review by facundobatista — APPROVED** [review]
Awesome, thanks!!

**Pull request merged**
